version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongodb-data:/data/db

volumes:
  postgres_data:
  mongodb-data: